### ISSUE TITLE
cloud custodian: dockerfile

### ISSUE THREAD

**Issue by sometheycallme** [cleanerbot/ansible-security#125]
create initial cloud custodian dockerfile for testing

**Comment by sometheycallme** [comment]
@jumanjiman 

basic dockerfile for cloud custodian.  volumes currently in same image.  once I get a few tests done in aws will separate.

thought you might be interested.

**Comment by sometheycallme** [comment]
https://github.com/cleanerbot/ansible-security/pull/124

I think the python2.7-alpine image has too many packages installed, make, gcc, etc.   Might need to peel that layer back and just try alpine3.4 with min pip installs.

**Comment by jumanjiman** [comment]
yeah, ship a runtime environment, not the build environment. see my docker-aws repo, which is based on alpine, not Python:alpine, for that exact reason.

my duo authproxy shows a second approach that uses a builder container then lifts the artifacts into a separate runtime container. it does not appear you need to do that for your current docker file, but I figured I'd mention it for completeness.
