### ISSUE TITLE
bats options to check dependencies

### ISSUE THREAD

**Issue by sometheycallme** [cleanerbot/ansible-security#21]
@jumanjiman 

related to #20 bats does offer some functions to check dependencies and load fixtures. 

haven't played with this yet.

"You can define special setup and teardown functions, which run before and after each test case, respectively. Use these to load fixtures, set up your environment, and clean up when you're done."

https://github.com/sstephenson/bats

**Comment by jumanjiman** [comment]
yep, and they work similar in concept to rspec `before(:each)` and `after(:each)`.

i use bats teardown/setup elsewhere at https://github.com/jumanjiman/docker-duoauthproxy/blob/master/test/test_authproxy.bats#L1-L11 (for example)

the teardown/setup functions are useful to guarantee that no state persists between tests that could yield false positives.
