### ISSUE TITLE
captain hook

### ISSUE THREAD

**Issue by sometheycallme** [cleanerbot/ansible-security#35]
@Jfach 

As mentioned.  When I build the branch https://github.com/cleanerbot/ansible-security/tree/captain-hook

I use CircleCI to run the build with SSH.  You should have access to circleCI with your github account.

First you have to accept being added to cleanerbot.  I just sent the invite.

**Comment by sometheycallme** [comment]
Once you accept, I'll add the project team members in CircleCI so that you can also build with circle.

**Comment by Jfach** [comment]
I'm in.

**Comment by sometheycallme** [comment]
to circle?

**Comment by Jfach** [comment]
I'm pretty sure. How would I know? I see cleanerbot as an organization my CircleCI

**Comment by Jfach** [comment]
![capture1](https://cloud.githubusercontent.com/assets/9730508/16092999/137e5b72-3308-11e6-8e88-6d75d53f150a.PNG)

**Comment by Jfach** [comment]
![capture2](https://cloud.githubusercontent.com/assets/9730508/16093169/d65c8a38-3308-11e6-9bd9-4079dd52fada.PNG)

**Comment by sometheycallme** [comment]
seems like you'll be able to follow the project.   try it.

when I go to Invite Teammates, CircleCI does not permit me to add you.

**Comment by Jfach** [comment]
Can confirm I'm able to follow the project.

**Comment by sometheycallme** [comment]
nice.  Now when you clone the build, you should be able to access the build spawned by circle via ssh.

<img width="1032" alt="screen shot 2016-06-15 at 2 54 27 pm" src="https://cloud.githubusercontent.com/assets/630113/16093265/28259e54-3309-11e6-9d2c-b3f13110b2c2.png">

**Comment by Jfach** [comment]
How should I clone the build? Am I making a fork or just rebuilding your latest build via SSH?

**Comment by sometheycallme** [comment]
>Now when you clone the build,

meant to say when you clone the repo/branch & then build...

**Comment by sometheycallme** [comment]
>Am I making a fork or just rebuilding your latest build via SSH?

either is fine.  the simple approach to try and see what is happening with captain hook is to just build the latest with SSH, then run these commands on the system  you ssh into:

```
docker build -f fixtures/Dockerfile -t ansible-data .
docker build --rm -f dockerfiles/dockerfile-ansible -t ansible-security .
docker run --volumes-from playbooks-data -t -i --entrypoint bash ansible-security
```

from there i followed the captain hook instructions.  at the very least it should respond to the command line 

I followed the instructions in the readme:

https://github.com/bketelsen/captainhook

Install and building from scratch creates the captain hook binary, but the CLI does not respond to ```captainhook``` commands.

Uncertain if it should (presumably it should).

**Comment by Jfach** [comment]
I can confirm that `go get github.com/bketelsen/captainhook` works, but indeed `captainhook` isn't recognized as a command.

**Comment by jumanjiman** [comment]
@Jfach @sometheycallme 

Did you set up your `~/.bashrc`?

here's mine in devenv:

```
user@devenv:~$ grep GO .bashrc 
export GOPATH=/home/user/gocode
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOBIN
PATH=$PATH:$HOME/.local/bin:$HOME/bin:$GOPATH/bin:$HOME/phabricator/arcanist/bin:$HOME/npm/bin
```

then:

```
user@devenv:~$ go get github.com/bketelsen/captainhook

user@devenv:~$ command -v captainhook
/home/user/gocode/bin/captainhook

user@devenv:~$ captainhook --help
Usage of captainhook:
  -configdir string
        config dir to use
  -echo
        send output from script
  -enable-proxy
        enable parsing of X-Forwarded-For header
  -listen-addr string
        http listen address (default "127.0.0.1:8080")
  -proxy-header string
        header to use for upstream client IP (default "X-Forwarded-For")
```

**Comment by sometheycallme** [comment]
ugh...I did not.  that is likely the cause.

**Comment by sometheycallme** [comment]
In the docker file we set 

ENV GOPATH=$HOME/go

Probably need GOBIN

**Comment by jumanjiman** [comment]
> Probably need GOBIN

and update `PATH`, too
or else --- after the build --- `mv $GOBIN/captainhook /usr/bin/`

**Comment by sometheycallme** [comment]
right.  so in dockerfile-ansible:

```
ENV GOPATH = $HOME/go
ENV GOBIN = $GOPATH/bin
ENV PATH = $PATH:$GOPATH

<snip>

      && mv $GOBIN/captainhook /usr/bin \
      && \
```

Im a bit confused on the final PATH environment variable.

**Comment by jumanjiman** [comment]
> Im a bit confused on the final PATH environment variable.

the shell uses PATH to find commands, so
append GOBIN to PATH to enable shell to find commands there

**Comment by sometheycallme** [comment]
Yes and your PATH is set above to

```PATH=$PATH:$GOBIN```

Then 

```PATH=$PATH:$HOME/.local/bin:$HOME/bin:$GOPATH/bin:$HOME/phabricator/arcanist/bin:$HOME/npm/bin```

Presumably we need to set both, and phabricator is not what we are using.

**Comment by sometheycallme** [comment]
IOW - I think all we need in the dockerfile is: 

```
ENV PATH=$PATH:$GOBIN
```

Am I wrong?

**Comment by Jfach** [comment]
Just spun up an AWS instance to test out the build process on a new machine. Same result. Going to attempt @jumanjiman suggestions and report back.

**Comment by jumanjiman** [comment]
> Am I wrong?

nope.

**Comment by sometheycallme** [comment]
Thanks, and to be sure I understand........

(http://unix.stackexchange.com/questions/26047/how-to-correctly-add-a-path-to-path)

this is you @jumanjiman simply appending multiple paths into one line here:

PATH=$PATH:$HOME/.local/bin:$HOME/bin:$GOPATH/bin:$HOME/phabricator/arcanist/bin:$HOME/npm/bin

**Comment by sometheycallme** [comment]
FYI Dockerfile looks like this:

FROM alpine:3.4
MAINTAINER Tim Kropp @sometheycallme
ENV GOPATH = $HOME/go
ENV GOBIN = $GOPATH/bin
ENV PATH = $PATH:$GOPATH

RUN apk upgrade --no-cache --available && \
    apk add --no-cache \
      python \
      py-pip \
      bash \
      git \
      go \
      && \
    apk add --no-cache -X 'http://dl-cdn.alpinelinux.org/alpine/edge/main' \
      'ansible>=2.0' \
      && pip install --upgrade pip \
      && pip install boto \
      && go get github.com/bketelsen/captainhook \
      && \
    :
WORKDIR /opt/ansible
EXPOSE 8080

**Comment by sometheycallme** [comment]
We'll need to care for the ANSIBLE path too.

**Comment by Jfach** [comment]
Is it possible to build captainhook from the dockerfile?

**Comment by sometheycallme** [comment]
ENV ANSIBLE_PATH = $HOME/opt/ansible

**Comment by sometheycallme** [comment]
>Is it possible to build captainhook from the dockerfile?

what we are trying to do is build captainhook into the Ansible controller image.

**Comment by sometheycallme** [comment]
Well the docker build looks better.  The next thing is the actual build of the binary.  I do this in the container in circle and it's fine.   Needs to be done in the dockerfile......

Here is what I did to get it to work in the circle image.

Check $PATH

```
bash-4.3# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/go
```
 
Check  $GOPATH

```
bash-4.3# echo $GOPATH
/go
```

Check current directory where binary is

```
bash-4.3# pwd
/go/src/github.com/bketelsen/captainhook
```

Check $GOBIN

```
bash-4.3# echo $GOBIN
/go/bin
```

As @jumanjiman suggested, move the binary over to /usr/bin and it works.

```
bash-4.3# mv captainhook /usr/bin
bash-4.3# cd /usr/bin
bash-4.3# captainhook --help
Usage of captainhook:
  -configdir string
    	config dir to use
  -echo
    	send output from script
  -enable-proxy
    	enable parsing of X-Forwarded-For header
  -listen-addr string
    	http listen address (default "127.0.0.1:8080")
  -proxy-header string
    	header to use for upstream client IP (default "X-Forwarded-For")
bash-4.3#
```

Test moving it over to /go/bin and it also works.

```
bash-4.3# cd /go/bin
bash-4.3# captainhook --help
Usage of captainhook:
  -configdir string
    	config dir to use
  -echo
    	send output from script
  -enable-proxy
    	enable parsing of X-Forwarded-For header
  -listen-addr string
    	http listen address (default "127.0.0.1:8080")
  -proxy-header string
    	header to use for upstream client IP (default "X-Forwarded-For")
bash-4.3# 
```
