### ISSUE TITLE
ansible-webserver: create simple python HTTP 

### ISSUE THREAD

**Issue by kropped** [cleanerbot/ansible-security#50]
@Jfach 

moving to a separate issue as this is a "pivot" feature:

something to consider

### get ip source

We can grab the source address with simpleHTTPServer

http://stackoverflow.com/questions/37055005/how-to-get-client-ip-from-simplehttpserver

### whitelist

Can also implement a whitelist function.
```
import string
whitelist = string.ascii_letters + string.digits + "' "
newtext = ''.join(c for c in newtext if c in whitelist)
```

### input validation

http://stackoverflow.com/questions/22418802/check-for-valid-sequence-input-in-python

#40

**Comment by Jfach** [comment]
I committed the initial model. Check out #51

**Comment by sometheycallme** [comment]
Nicely done, we can work together today to find some basic Ansible patterns to commit to the repo, and hopefully by the end of the day use the pipeline to spawn a VPC in AWS.

**Comment by sometheycallme** [comment]
done.  We'll open a new issue for further modifications.
