### ISSUE TITLE
autostager: upon entrypoint run on loop

### ISSUE THREAD

**Issue by sometheycallme** [cleanerbot/ansible-security#63]
@Jfach 

Reminder:  When we run the docker image for autostager we want to run it on a repeating timer, like every 30 seconds or so.   We can always adjust the timer.

**Comment by Jfach** [comment]
On it.

**Comment by Jfach** [comment]
Going to have it be set by an environment variable, such as `refresh_time`. If the environment variable doesn't exist, it will default to 30 seconds.

**Comment by Jfach** [comment]
Implemented in autostager, https://github.com/Jfach/autostager/commit/6c5c402ab70b230559177d493a442aac706eb9ce

Now I have to make sure the dockerfile for autostager has this env variable and runs autostager.py upon entry.

**Comment by Jfach** [comment]
@sometheycallme one issue with this is that we cant simply have 
`ENTRYPOINT ["python", "autostager.autostager.py"]`
without first loading in the environment variables required for autostager...

**Comment by sometheycallme** [comment]
>loading in the environment variables required for autostager...

Achieved with

```
docker create -v /etc/ansible --name ansible-data alpine true
docker run --volumes-from ansible-data:rw --env-file /home/core/env_vars -t -i autostager
```

I think

**Comment by sometheycallme** [comment]
#40

**Comment by sometheycallme** [comment]
@Jfach 

This one is done too, correct?

**Comment by Jfach** [comment]
done.
