### ISSUE TITLE
ansible-controller: run webserver.py upon entry

### ISSUE THREAD

**Issue by sometheycallme** [cleanerbot/ansible-security#65]
@Jfach 

similar to issue #63 we'll do the same when we invoke the ansible-controller.

Once we complete this issue, we can probably do a hello-world run of the pipeline from the coreos-pipeline host in our devenv.

Autostager is working well on this repository.

**Comment by sometheycallme** [comment]
#40

**Comment by Jfach** [comment]
got it working locally:
```
core@coreos-pipeline ~/ansible-security $ docker run -i ansible-controller
Listening on localhost:8080
```

**Comment by Jfach** [comment]
#68 and 880d5c7 closes this issue.

**Comment by sometheycallme** [comment]
NIce.  Fetch and rebase.
