### ISSUE TITLE
ansible-security: playbook to clone repos

### ISSUE THREAD

**Issue by sometheycallme** [cleanerbot/ansible-security#66]
Here is an example playbook for cloning repos.

https://gist.github.com/mblarsen/62d2c0451e69a607a66a

**Comment by vpalacio** [comment]
I opened an issue in the issue repo with a similar example. Use that


Victor Palacio
Network Engineering
ISE

On Jun 24, 2016, at 3:49 PM, Tim Kropp <notifications@github.com<mailto:notifications@github.com>> wrote:


Here is an example playbook for cloning repos.

https://gist.github.com/mblarsen/62d2c0451e69a607a66a<https://urldefense.proofpoint.com/v2/url?u=https-3A__gist.github.com_mblarsen_62d2c0451e69a607a66a&d=CwMCaQ&c=j0C83om1U8eJ3TCW06XWZw&r=dtQ2VbizKcahoyIkJwD9Xg&m=cXEokjkmxlMSCs0xiBRmxiRJXFc_nyb0tbGcG9wHIbs&s=Abqv2ILcIldonUvrTbgjVU-5iqtiIjDNq4MX_2sympM&e=>

**Comment by sometheycallme** [comment]
Nicely documented too:

Just thought I'd share:

With ansible installed, I can have ansible clone my favorite repos all in one shot. 

Ansible playbook:
```
Colossus:tmp vpalacio$ cat clone_gh_repos.yml 
---

  - name: Clone git repos
    hosts: localhost
    connection: local
    gather_facts: False
    vars_files:
      - vars/main.yml

    tasks:
     - name: Cloning repos
       git: repo=git@github.com:/{{ item.org }}/{{ item.repo }} 
            dest=/tmp/test/{{ item.repo }} 
            accept_hostkey=yes
            force=yes
       with_items: '{{ repo_list }}'
```

variable file holding github org and repo names in folder/file called vars/main.yml:
```
---
   repo_list:
     - { org: 'vpalacio', repo: 'toolbox' }
```

only thing in my inventory file is my localhost that I'm running ansible on:
```
[myhosts]
localhost
```

Checking to see if my destination folder has anything, nope!
```
Colossus:tmp vpalacio$ find test
find: test: No such file or directory
```

Running my playbook:
```
Colossus:tmp vpalacio$ ansible-playbook -i inventory clone_gh_repos.yml 

PLAY [Clone git repos] *********************************************************

TASK [Cloning repos] ***********************************************************
changed: [localhost] => (item={u'repo': u'toolbox', u'org': u'vpalacio'})

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0   
```

Success:
```
Colossus:tmp vpalacio$ find test
test
test/toolbox
test/toolbox/.git
test/toolbox/.git/branches
<snip>
```

Ideally I can version control with git my playbooks and only have to change the variable file to include more of my favorite repos. Then run my playbook to make sure I have the clone with the latest updates!


reference: http://docs.ansible.com/ansible/git_module.html

**Comment by sometheycallme** [comment]
This is a perfect hello world test candidate for the pipeline!

**Comment by sometheycallme** [comment]
works:

#73 #80
