### ISSUE TITLE
webserver: elif syntax error

### ISSUE THREAD

**Issue by sometheycallme** [cleanerbot/ansible-security#98]
@jumanjiman @Jfach 

post pep8 we have likely have an indentation issue.

getting this running the web server locally (python version 2.7.10).  Will attempt to replicate in devenv.

```
sometheycallme:ansible-security TimKropp$ webserver/server.py 
  File "webserver/server.py", line 101
    elif request_path == '/run':
       ^
SyntaxError: invalid syntax
sometheycallme:ansible-security TimKropp$ 
```

Commenting out the elif works.

```
sometheycallme:ansible-security TimKropp$ webserver/server.py 
Listening on localhost:8080


```

**Comment by jumanjiman** [comment]
i see the issue and can clean it up a bit 😄

**Comment by jumanjiman** [comment]
@sometheycallme Take a look at https://github.com/cleanerbot/ansible-security/pull/102 and see if it fixes the issue you saw here.
